### ISSUE TITLE
Inference error on Windows - Permission denied

### ISSUE THREAD

**Issue by Dragos-Stan** [IDEA-Research/GroundingDINO#14]
Hello and thanks for your absolutely amazing work !

Although on an OracleVM with Ubuntu-22 over W10 works ok, on Windows 10 - conda environment - I encounter the following error : 
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\drago\\AppData\\Local\\Temp\\tmp3ta82pyj\\tmpvv_bru9r.py'

full description:
"(ZeroShot_GroundingDINO) C:\ML_Projects\Computer_Vision\GroundingDINO>python demo/inference_on_a_image.py --config_file groundingdino/config/GroundingDINO_SwinT_OGC.py --checkpoint_path weights/groundingdino_swint_ogc.pth --image_path images/Truck1.jpg --text_prompt truck --output_dir inference/images --box_threshold 0.3 --text_threshold 0.25
Traceback (most recent call last):
  File "C:\ML_Projects\Computer_Vision\GroundingDINO\demo\inference_on_a_image.py", line 153, in <module>
    model = load_model(config_file, checkpoint_path, cpu_only=args.cpu_only)
  File "C:\ML_Projects\Computer_Vision\GroundingDINO\demo\inference_on_a_image.py", line 73, in load_model
    args = SLConfig.fromfile(model_config_path)
  File "c:\ml_projects\computer_vision\groundingdino\groundingdino\util\slconfig.py", line 182, in fromfile
    cfg_dict, cfg_text = SLConfig._file2dict(filename)
  File "c:\ml_projects\computer_vision\groundingdino\groundingdino\util\slconfig.py", line 83, in _file2dict
    shutil.copyfile(filename, osp.join(temp_config_dir, temp_config_name))
  File "C:\Users\drago\anaconda3\envs\ZeroShot_GroundingDINO\lib\shutil.py", line 266, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\drago\\AppData\\Local\\Temp\\tmp3ta82pyj\\tmpvv_bru9r.py'

The same error running as admin.

Thanks for help.

Dragos

**Comment by Dragos-Stan** [comment]
Thanks !
