### ISSUE TITLE
NameError: name '_C' is not defined

### ISSUE THREAD

**Issue by LayanNCAI** [IDEA-Research/GroundingDINO#142]
Error:
`NameError: name '_C' is not defined`

Full traceback:

> warnings.warn(
/home/alabl0a/miniconda3/envs/detgpt/lib/python3.9/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
Traceback (most recent call last):
  File "/home/alabl0a/miniconda3/envs/detgpt/lib/python3.9/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/alabl0a/miniconda3/envs/detgpt/lib/python3.9/site-packages/gradio/blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "/home/alabl0a/miniconda3/envs/detgpt/lib/python3.9/site-packages/gradio/blocks.py", line 915, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/alabl0a/miniconda3/envs/detgpt/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/alabl0a/miniconda3/envs/detgpt/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/user/miniconda3/envs/detgpt/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/user/user/DetGPT/demo_detgpt.py", line 165, in run_grounding
    boxes, logits, phrases = predict(detector, image_tensor, categories, box_threshold, text_threshold,
  File "/user/user/DetGPT/GroundingDINO/groundingdino/util/inference.py", line 66, in predict
    outputs = model(image[None], captions=[caption])
  File "/home/user/miniconda3/envs/detgpt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/user/user/DetGPT/GroundingDINO/groundingdino/models/GroundingDINO/groundingdino.py", line 313, in forward
    hs, reference, hs_enc, ref_enc, init_box_proposal = self.transformer(
  File "/home/user/miniconda3/envs/detgpt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/user/user/DetGPT/GroundingDINO/groundingdino/models/GroundingDINO/transformer.py", line 258, in forward
    memory, memory_text = self.encoder(
  File "/home/user/miniconda3/envs/detgpt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/user/user/DetGPT/GroundingDINO/groundingdino/models/GroundingDINO/transformer.py", line 576, in forward
    output = checkpoint.checkpoint(
  File "/home/user/miniconda3/envs/detgpt/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/user/miniconda3/envs/detgpt/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/user/miniconda3/envs/detgpt/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/user/miniconda3/envs/detgpt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/user/user/DetGPT/GroundingDINO/groundingdino/models/GroundingDINO/transformer.py", line 785, in forward
    src2 = self.self_attn(
  File "/home/user/miniconda3/envs/detgpt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/user/user/DetGPT/GroundingDINO/groundingdino/models/GroundingDINO/ms_deform_attn.py", line 338, in forward
    output = MultiScaleDeformableAttnFunction.apply(
  File "/home/user/miniconda3/envs/detgpt/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File `"/user/user/DetGPT/GroundingDINO/groundingdino/models/GroundingDINO/ms_deform_attn.py",` line 53, in forward
    output = _C.ms_deform_attn_forward(

**Comment by BadrEssabri** [comment]
https://github.com/IDEA-Research/GroundingDINO/issues/8#issuecomment-1541892708 

This solution fixed it for me.

**Comment by arbaz-pivotchain** [comment]
This occurs because as it says in code it fails to load custom C++ ops. Check your virtual environment carefully. Or make new one and use command "pip3 install -q -e ." to install every module and stuff needed
