### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

### ISSUE THREAD

**Issue by 6black66** [IDEA-Research/GroundingDINO#155]
Found GroundingDINO in pip. Verifying if dynamic library build success.
GroundingDINO dynamic library have been successfully built.
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinT_OGC (694MB)
final text_encoder_type: bert-base-uncased
Traceback (most recent call last):
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\extensions\sd-webui-segment-anything\scripts\sam.py", line 247, in dino_predict
    boxes_filt, install_success = dino_predict_internal(input_image, dino_model_name, text_prompt, box_threshold)
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\extensions\sd-webui-segment-anything\scripts\dino.py", line 173, in dino_predict_internal
    dino_model = load_dino_model(dino_model_name, install_success)
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\extensions\sd-webui-segment-anything\scripts\dino.py", line 119, in load_dino_model
    dino = build_model(args)
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\groundingdino\models\__init__.py", line 17, in build_model
    model = build_func(args)
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\groundingdino\models\GroundingDINO\groundingdino.py", line 371, in build_groundingdino
    model = GroundingDINO(
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\groundingdino\models\GroundingDINO\groundingdino.py", line 108, in __init__
    self.bert = get_tokenlizer.get_pretrained_language_model(text_encoder_type)
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\groundingdino\util\get_tokenlizer.py", line 25, in get_pretrained_language_model
    return BertModel.from_pretrained(text_encoder_type)
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\transformers\modeling_utils.py", line 2169, in from_pretrained
    if has_file(pretrained_model_name_or_path, TF2_WEIGHTS_NAME, **has_file_kwargs):
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\transformers\utils\hub.py", line 609, in has_file
    r = requests.head(url, headers=headers, allow_redirects=False, proxies=proxies, timeout=10)
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\requests\api.py", line 104, in head
    return request('head', url, **kwargs)
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "E:\sd-webui-aki\sd-webui-aki-v4.1\python\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by Fatal-Eror** [comment]
同样遇到这个问题，并且我也勾选了bypass c++problem，也手动下载了两个模型到\sd-webui-aki-v4.2\extensions\sd-webui-segment-anything\models\grounding-dino，但插件仍然想自己上抱脸下载模型然后失败报错

**Comment by beamovo** [comment]
开全局代理
