### ISSUE TITLE
Real time/video inference?

### ISSUE THREAD

**Issue by kenhuangsy** [IDEA-Research/GroundingDINO#159]
Hey, I'm wondering if it is possible to run inference in real-time or in a video? Like similar to how you would with YOLO?

**Comment by aymenbenammar** [comment]
Yes, in fact it is possible but it's not as fast as YOLO. 
Just try this code  
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()

    image_source, image = load_image(frame)

    boxes,  accuracy, obj_name=predict(
        model=mymodel,
        image=image,
        caption=TEXT_PROMPT,
        box_threshold=BOX_TRESHOLD,
        text_threshold=TEXT_TRESHOLD
    )

    annotated_frame = annotate(image_source=image_source, boxes=boxes, logits=accuracy, phrases=obj_name)
    print(obj_name)
    cv2.imshow('frame', annotated_frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

**Comment by kenhuangsy** [comment]
@aymenbenammar thank you! I love you man!

**Comment by Pratik-Ghute** [comment]
for this same code I am getting this error:


Traceback (most recent call last):
  File "test.py", line 26, in <module>
    image_source,image = load_image(frame)
  File "/home/thinkpad/Desktop/unknown object detection/Dino/GroundingDINO/groundingdino/util/inference.py", line 47, in load_image
    image_source = Image.open(image_path).convert("RGB")
  File "/home/thinkpad/.local/lib/python3.8/site-packages/PIL/Image.py", line 3224, in open
    fp = io.BytesIO(fp.read())
AttributeError: 'numpy.ndarray' object has no attribute 'read'

**Comment by llealgt** [comment]
@Pratik-Ghute were you able to solve it? I have the same issue. 
@aymenbenammar any recommendations? Based on the error message i t looks as load_image expects an image path as argument, which it then reads using Image.open, so I don't think that passing the frame will work.

Thanks!!

**Comment by Pratik-Ghute** [comment]
@llealgt Yes, I did have solved it back then, I think it was just converting cv2's video frame into PIL image

**Comment by jamesbaker1** [comment]
This is awesome! How many approx FPS can grounding dino get on a 4090?
