### ISSUE TITLE
torch not installed as dependencies when installing groundingdino

### ISSUE THREAD

**Issue by XkunW** [IDEA-Research/GroundingDINO#170]
The following error occurs if torch was not installed in the environment prior to the installation of groundingdino
`Collecting git+https://github.com/IDEA-Research/GroundingDINO.git
  Cloning https://github.com/IDEA-Research/GroundingDINO.git to /tmp/pip-req-build-cqbznast
  Running command git clone --filter=blob:none --quiet https://github.com/IDEA-Research/GroundingDINO.git /tmp/pip-req-build-cqbznast
  Resolved https://github.com/IDEA-Research/GroundingDINO.git to commit 6c27bc76b9c7252c201e0b8c680d7349a7a0aaf8
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-cqbznast/setup.py", line 27, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by giladElichai** [comment]
@XkunW 
same issue here, was you able to solve it?

**Comment by zhangjingxian1998** [comment]
> @XkunW
> same issue here, was you able to solve it?

just run `pip install -r requirement.txt` before `pip install -e .`

**Comment by M-Colley** [comment]
> > @XkunW
> > same issue here, was you able to solve it?
> 
> just run `pip install -r requirement.txt` before `pip install -e .`

This did not resolve the issue for me...

I am on Windows, have torch 2.0.1 installed, CUDA_HOME is set...

**Comment by zhangjingxian1998** [comment]
> This did not resolve the issue for me...
> 
> I am on Windows, have torch 2.0.1 installed, CUDA_HOME is set...

My enviroment is ubuntu, maybe something is different.

**Comment by noahdasanaike** [comment]
Try running `python3 setup.py install` after installing torch

**Comment by NTL-Remi** [comment]
Running `setup.py` manually has been [deprecated](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#what-commands-should-be-used-instead) for a few years now, I think.

The thing is that the current [`setup.py` expects `torch` to be installed](https://github.com/IDEA-Research/GroundingDINO/blob/856dde20aee659246248e20734ef9ba5214f5e44/setup.py#L30-L37) before defining the `setup()` function, which is where [dependencies are listed](https://github.com/IDEA-Research/GroundingDINO/blob/856dde20aee659246248e20734ef9ba5214f5e44/setup.py#L211).
It uses `torch` to compile an extension either for CUDA or CPU depending on GPU availability.
This means that torch is not only a runtime dependency, but also a build dependency.

I don't have experience in Python packaging, so it may be that I'm totally off, but I think there may be something to try with just having a `pyproject.toml` listing both `torch` and `setuptools` as build dependencies.

**Comment by tanay-kondapally** [comment]
Any luck here?

**Comment by Cynthia11281128** [comment]
> Try running `python3 setup.py install` after installing torch

WORKS for me!! THANKS!

**Comment by ChikaYan** [comment]
> python3 setup.py install

This worked for me

**Comment by thilinawee** [comment]
> Try running `python3 setup.py install` after installing torch

After hours of trying various fixes mentioned in the threads, this worked like a charm !!!!!. Thanks @noahdasanaike
