### ISSUE TITLE
why。。。。

### ISSUE THREAD

**Issue by tangbob** [IDEA-Research/GroundingDINO#171]
PS G:\BaiduSyncdisk\AIproject\GroundingDINO> pip install -e .
Looking in indexes: https://pypi.org/simplehttps://pypi.doubanio.com/simple, https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///G:/BaiduSyncdisk/AIproject/GroundingDINO
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "C:\Program Files\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Program Files\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-ftmx40ze\overlay\Lib\site-packages\setuptools\build_meta.py", line 450, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-ftmx40ze\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-ftmx40ze\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-ftmx40ze\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-ftmx40ze\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 27, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by zhangjingxian1998** [comment]
run `pip install -r requirement.txt` before `pip install -e .`

**Comment by SimJav** [comment]
Still the same error after  pip install -r requirement.txt

**Comment by 1benwu1** [comment]
> Still the same error after pip install -r requirement.txt

how did you solve this problem in the end.... I'm facing the exact same problem as you.  pretty annoying

**Comment by zhangjingxian1998** [comment]
> > Still the same error after pip install -r requirement.txt
> 
> how did you solve this problem in the end.... I'm facing the exact same problem as you. pretty annoying

are you sure the same error? this should be solved after install torch

**Comment by 1benwu1** [comment]
> > > Still the same error after pip install -r requirement.txt
> > 
> > 
> > how did you solve this problem in the end.... I'm facing the exact same problem as you. pretty annoying
> 
> are you sure the same error? this should be solved after install torch

pretty god damn sure... i had to switch to another device . 换了台设备跑了

**Comment by zhangjingxian1998** [comment]
> > > > Still the same error after pip install -r requirement.txt
> > > 
> > > 
> > > how did you solve this problem in the end.... I'm facing the exact same problem as you. pretty annoying
> > 
> > 
> > are you sure the same error? this should be solved after install torch
> 
> pretty god damn sure... i had to switch to another device . 换了台设备跑了

真邪门儿
