### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by skylning** [IDEA-Research/GroundingDINO#206]
i install the package,and get error message as follow:
 Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Lining\AppData\Local\Temp\pip-install-godyuld_\groundingdino-py_3354b3ab580b4d9f8d19e2f3a8521336\setup.py", line 41, in <module>
          readme = readme_file.read()
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 2878: illegal multibyte sequence

**Comment by rcfcu2000** [comment]
Assuming this is windows platform, you will have to change the system locale to en-US(settings->time and language->language & region->administrative language settings) and then install it. After the installation is done, you can switch the locale back

**Comment by EricoZhao** [comment]
> 假设这是 Windows 平台，则必须将系统区域设置为 en-US（设置->时间和语言->语言和区域->管理语言设置），然后安装。安装完成后，您可以将区域设置切换回来

![image](https://github.com/user-attachments/assets/1a1f1628-e3e9-459b-b355-d928f7d208db)
