### ISSUE TITLE
stable-diffusion-webui install error

### ISSUE THREAD

**Issue by mayjack0312** [IDEA-Research/GroundingDINO#213]
pip install file:///F:/stable-diffusion-webui/extensions/sd-webui-segment-anything/GroundingDINO
DEPRECATION: Loading egg at c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages\click-8.1.7-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
DEPRECATION: Loading egg at c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages\face_recognition-1.0.0-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
DEPRECATION: Loading egg at c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages\face_recognition_models-0.3.0-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing f:\stable-diffusion-webui\extensions\sd-webui-segment-anything\groundingdino
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Users\LMY\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\LMY\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\LMY\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\LMY\AppData\Local\Temp\pip-build-env-m4dd3jud\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\LMY\AppData\Local\Temp\pip-build-env-m4dd3jud\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\LMY\AppData\Local\Temp\pip-build-env-m4dd3jud\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\LMY\AppData\Local\Temp\pip-build-env-m4dd3jud\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 27, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by mayjack0312** [comment]
torch has been installed and updated to the latest version
```
pip install torch
DEPRECATION: Loading egg at c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages\click-8.1.7-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
DEPRECATION: Loading egg at c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages\face_recognition-1.0.0-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
DEPRECATION: Loading egg at c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages\face_recognition_models-0.3.0-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting torch
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d0/c8/f0dc8642e3ce0a3ae5f05e5149ab9df5375d569294f7be9a1ab1d95a1d76/torch-2.0.1-cp311-cp311-win_amd64.whl (172.3 MB)
Requirement already satisfied: filelock in c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages (from torch) (3.12.2)
Requirement already satisfied: typing-extensions in c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages (from torch) (4.7.1)
Requirement already satisfied: sympy in c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages (from torch) (1.12)
Collecting networkx (from torch)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a8/05/9d4f9b78ead6b2661d6e8ea772e111fc4a9fbd866ad0c81906c11206b55e/networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting jinja2 (from torch)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/bc/c3/f068337a370801f372f2f8f6bad74a5c140f6fda3d9de154052708dd3c65/Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/be/bb/08b85bc194034efbf572e70c3951549c8eca0ada25363afc154386b5390a/MarkupSafe-2.1.3-cp311-cp311-win_amd64.whl (17 kB)
Requirement already satisfied: mpmath>=0.19 in c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages (from sympy->torch) (1.3.0)
Installing collected packages: networkx, MarkupSafe, jinja2, torch
Successfully installed MarkupSafe-2.1.3 jinja2-3.1.2 networkx-3.1 torch-2.0.1
```
```
pip install --upgrade torch
DEPRECATION: Loading egg at c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages\click-8.1.7-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
DEPRECATION: Loading egg at c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages\face_recognition-1.0.0-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
DEPRECATION: Loading egg at c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages\face_recognition_models-0.3.0-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: torch in c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages (2.0.1)
Requirement already satisfied: filelock in c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages (from torch) (3.12.2)
Requirement already satisfied: typing-extensions in c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages (from torch) (4.7.1)
Requirement already satisfied: sympy in c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages (from torch) (1.12)
Requirement already satisfied: networkx in c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages (from torch) (3.1)
Requirement already satisfied: jinja2 in c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages (from torch) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in c:\users\lmy\appdata\local\programs\python\python311\lib\site-packages (from sympy->torch) (1.3.0)
```
