### ISSUE TITLE
infrence the python demo was wrong!!!!

### ISSUE THREAD

**Issue by sssssshf** [IDEA-Research/GroundingDINO#218]
the infrence code :
from groundingdino.util.inference import load_model, load_image, predict, annotate
import cv2

model = load_model("groundingdino/config/GroundingDINO_SwinT_OGC.py", "weights/groundingdino_swint_ogc.pth")

IMAGE_PATH = "0.jpg"
TEXT_PROMPT = "cat"
BOX_TRESHOLD = 0.35
TEXT_TRESHOLD = 0.25

image_source, image = load_image(IMAGE_PATH)

boxes, logits, phrases = predict(
    model=model,
    image=image,
    caption=TEXT_PROMPT,
    box_threshold=BOX_TRESHOLD,
    text_threshold=TEXT_TRESHOLD
)

annotated_frame = annotate(image_source=image_source, boxes=boxes, logits=logits, phrases=phrases)
cv2.imwrite("annotated_image.jpg", annotated_frame)

can't laod model line. the wrong is show :

OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like bert-base-uncased is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

how to selvo this problem????  anyone can help me

**Comment by xjtupanda** [comment]
This is because the Bert encoder still needs to be downloaded from huggingface. You may download it on [Link](https://huggingface.co/bert-base-uncased/tree/main) and put those files into ```~/.cache/huggingface/hub/models--bert-base-uncased/```

**Comment by xjtupanda** [comment]
I solved it by downloading the files specified above and change ```text_encoder_type``` in https://github.com/IDEA-Research/GroundingDINO/blob/60d796825e1266e56f7e4e9e00e88de662b67bd3/groundingdino/models/GroundingDINO/groundingdino.py#L107-L108 to the path of downloaded files.

**Comment by sssssshf** [comment]
> I solved it by downloading the files specified above and change `text_encoder_type` in
> 
> https://github.com/IDEA-Research/GroundingDINO/blob/60d796825e1266e56f7e4e9e00e88de662b67bd3/groundingdino/models/GroundingDINO/groundingdino.py#L107-L108
> 
> to the path of downloaded files.

you means replace 'text_encoder_type' with downloaded files. but What exactly is it.
 self.tokenizer = get_tokenlizer.get_tokenlizer('') 
 self.bert = get_tokenlizer.get_pretrained_language_model('') 
What should I write in parentheses???

**Comment by xjtupanda** [comment]
Download the files and save them to a local folder; then put in parentheses the path of the folder.

**Comment by sssssshf** [comment]
> Download the files and save them to a local folder; then put in parentheses the path of the folder.

I solved this pbl.thanks..谢谢大老表

**Comment by LiJunY** [comment]
> Download the files and save them to a local folder; then put in parentheses the path of the folder.

when i down all the files, and put in parentheses the path of the folder:


ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported

**Comment by xjtupanda** [comment]
> > Download the files and save them to a local folder; then put in parentheses the path of the folder.
> 
> when i down all the files, and put in parentheses the path of the folder: @xjtupanda @sssssshf
> 
> ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported

I guess this method only works for the official implementation. Since you're using another tokenizer, rather than the 'bert-base-uncased', you may need to figure out how to adapt.

**Comment by yuhao20** [comment]
> > Download the files and save them to a local folder; then put in parentheses the path of the folder.
> 
> I solved this pbl.thanks..谢谢大老表

halo, can u explain how you solve this pbl in detail? thanks!!!

**Comment by WanFeng123313** [comment]
> > > Download the files and save them to a local folder; then put in parentheses the path of the folder.
> > 
> > 
> > I solved this pbl.thanks..谢谢大老表
> 
> halo, can u explain how you solve this pbl in detail? thanks!!!

![image](https://github.com/IDEA-Research/GroundingDINO/assets/81793539/8fba8c05-417a-4815-ab25-80a211051c31)
like this

**Comment by yuhao20** [comment]
> > > > Download the files and save them to a local folder; then put in parentheses the path of the folder.
> > > 
> > > 
> > > I solved this pbl.thanks..谢谢大老表
> > 
> > 
> > halo, can u explain how you solve this pbl in detail? thanks!!!
> 
> ![image](https://user-images.githubusercontent.com/81793539/274125212-8fba8c05-417a-4815-ab25-80a211051c31.png) like this

thanks! But I do this then got the problem as below? Do you know why? 

(GroundDINO3.8) ubuntu@SYS-7049GP:~/jyh/Gounding_DINO/GroundingDINO$ python demo/inference_on_a_image.py -c groundingdino/config/GroundingDINO_SwinT_OGC.py -p weights/groundingdino_swint_ogc.pth -i .asset/cat_dog.jpeg -o 'output' -t 'chair'
/home/ubuntu/anaconda3/envs/GroundDINO3.8/lib/python3.8/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
final text_encoder_type: /home/ubuntu/jyh/Gounding_DINO/GroundingDINO/.cache/huggingface/hub/models--bert-base-uncased
Traceback (most recent call last):
  File "demo/inference_on_a_image.py", line 201, in <module>
    model = load_model(config_file, checkpoint_path, cpu_only=args.cpu_only)
  File "demo/inference_on_a_image.py", line 81, in load_model
    model = build_model(args)
  File "/home/ubuntu/jyh/Gounding_DINO/GroundingDINO/groundingdino/models/__init__.py", line 17, in build_model
    model = build_func(args)
  File "/home/ubuntu/jyh/Gounding_DINO/GroundingDINO/groundingdino/models/GroundingDINO/groundingdino.py", line 394, in build_groundingdino
    model = GroundingDINO(
  File "/home/ubuntu/jyh/Gounding_DINO/GroundingDINO/groundingdino/models/GroundingDINO/groundingdino.py", line 113, in __init__
    self.bert = get_tokenlizer.get_pretrained_language_model("/home/ubuntu/jyh/Gounding_DINO/GroundingDINO/.cache/huggingface/hub/models--bert-base-uncased")       
  File "/home/ubuntu/jyh/Gounding_DINO/GroundingDINO/groundingdino/util/get_tokenlizer.py", line 25, in get_pretrained_language_model
    return BertModel.from_pretrained(text_encoder_type)
  File "/home/ubuntu/anaconda3/envs/GroundDINO3.8/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3019, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/home/ubuntu/anaconda3/envs/GroundDINO3.8/lib/python3.8/site-packages/transformers/modeling_utils.py", line 463, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
**safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer**

**Comment by yuhao20** [comment]
> > > > > Download the files and save them to a local folder; then put in parentheses the path of the folder.
> > > > 
> > > > 
> > > > I solved this pbl.thanks..谢谢大老表
> > > 
> > > 
> > > halo, can u explain how you solve this pbl in detail? thanks!!!
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/81793539/274125212-8fba8c05-417a-4815-ab25-80a211051c31.png) like this
> 
> thanks! But I do this then got the problem as below? Do you know why?
> 
> (GroundDINO3.8) ubuntu@SYS-7049GP:~/jyh/Gounding_DINO/GroundingDINO$ python demo/inference_on_a_image.py -c groundingdino/config/GroundingDINO_SwinT_OGC.py -p weights/groundingdino_swint_ogc.pth -i .asset/cat_dog.jpeg -o 'output' -t 'chair' /home/ubuntu/anaconda3/envs/GroundDINO3.8/lib/python3.8/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:2228.) return _VF.meshgrid(tensors, **kwargs) # type: ignore[attr-defined] final text_encoder_type: /home/ubuntu/jyh/Gounding_DINO/GroundingDINO/.cache/huggingface/hub/models--bert-base-uncased Traceback (most recent call last): File "demo/inference_on_a_image.py", line 201, in model = load_model(config_file, checkpoint_path, cpu_only=args.cpu_only) File "demo/inference_on_a_image.py", line 81, in load_model model = build_model(args) File "/home/ubuntu/jyh/Gounding_DINO/GroundingDINO/groundingdino/models/**init**.py", line 17, in build_model model = build_func(args) File "/home/ubuntu/jyh/Gounding_DINO/GroundingDINO/groundingdino/models/GroundingDINO/groundingdino.py", line 394, in build_groundingdino model = GroundingDINO( File "/home/ubuntu/jyh/Gounding_DINO/GroundingDINO/groundingdino/models/GroundingDINO/groundingdino.py", line 113, in **init** self.bert = get_tokenlizer.get_pretrained_language_model("/home/ubuntu/jyh/Gounding_DINO/GroundingDINO/.cache/huggingface/hub/models--bert-base-uncased") File "/home/ubuntu/jyh/Gounding_DINO/GroundingDINO/groundingdino/util/get_tokenlizer.py", line 25, in get_pretrained_language_model return BertModel.from_pretrained(text_encoder_type) File "/home/ubuntu/anaconda3/envs/GroundDINO3.8/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3019, in from_pretrained state_dict = load_state_dict(resolved_archive_file) File "/home/ubuntu/anaconda3/envs/GroundDINO3.8/lib/python3.8/site-packages/transformers/modeling_utils.py", line 463, in load_state_dict with safe_open(checkpoint_file, framework="pt") as f: **safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer**

I have solved this problem by re-downloading the file below and use scp to my host path "/home/ubuntu/jyh/Gounding_DINO/GroundingDINO/.cache/huggingface/hub/models--bert-base-uncased". Then its ok.
![image](https://github.com/IDEA-Research/GroundingDINO/assets/89685634/bd75c91b-c061-4c12-bb65-e3c3f528c85a)

**Comment by Brando1025** [comment]
> > > > > > Download the files and save them to a local folder; then put in parentheses the path of the folder.
> > > > > 
> > > > > 
> > > > > I solved this pbl.thanks..谢谢大老表
> > > > 
> > > > 
> > > > halo, can u explain how you solve this pbl in detail? thanks!!!
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/81793539/274125212-8fba8c05-417a-4815-ab25-80a211051c31.png) like this
> > 
> > 
> > thanks! But I do this then got the problem as below? Do you know why?
> > (GroundDINO3.8) ubuntu@SYS-7049GP:~/jyh/Gounding_DINO/GroundingDINO$ python demo/inference_on_a_image.py -c groundingdino/config/GroundingDINO_SwinT_OGC.py -p weights/groundingdino_swint_ogc.pth -i .asset/cat_dog.jpeg -o 'output' -t 'chair' /home/ubuntu/anaconda3/envs/GroundDINO3.8/lib/python3.8/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:2228.) return _VF.meshgrid(tensors, **kwargs) # type: ignore[attr-defined] final text_encoder_type: /home/ubuntu/jyh/Gounding_DINO/GroundingDINO/.cache/huggingface/hub/models--bert-base-uncased Traceback (most recent call last): File "demo/inference_on_a_image.py", line 201, in model = load_model(config_file, checkpoint_path, cpu_only=args.cpu_only) File "demo/inference_on_a_image.py", line 81, in load_model model = build_model(args) File "/home/ubuntu/jyh/Gounding_DINO/GroundingDINO/groundingdino/models/**init**.py", line 17, in build_model model = build_func(args) File "/home/ubuntu/jyh/Gounding_DINO/GroundingDINO/groundingdino/models/GroundingDINO/groundingdino.py", line 394, in build_groundingdino model = GroundingDINO( File "/home/ubuntu/jyh/Gounding_DINO/GroundingDINO/groundingdino/models/GroundingDINO/groundingdino.py", line 113, in **init** self.bert = get_tokenlizer.get_pretrained_language_model("/home/ubuntu/jyh/Gounding_DINO/GroundingDINO/.cache/huggingface/hub/models--bert-base-uncased") File "/home/ubuntu/jyh/Gounding_DINO/GroundingDINO/groundingdino/util/get_tokenlizer.py", line 25, in get_pretrained_language_model return BertModel.from_pretrained(text_encoder_type) File "/home/ubuntu/anaconda3/envs/GroundDINO3.8/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3019, in from_pretrained state_dict = load_state_dict(resolved_archive_file) File "/home/ubuntu/anaconda3/envs/GroundDINO3.8/lib/python3.8/site-packages/transformers/modeling_utils.py", line 463, in load_state_dict with safe_open(checkpoint_file, framework="pt") as f: **safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer**
> 
> I have solved this problem by re-downloading the file below and use scp to my host path "/home/ubuntu/jyh/Gounding_DINO/GroundingDINO/.cache/huggingface/hub/models--bert-base-uncased". Then its ok. ![image](https://private-user-images.githubusercontent.com/89685634/274205158-bd75c91b-c061-4c12-bb65-e3c3f528c85a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTA0MjksIm5iZiI6MTcwNTA1MDEyOSwicGF0aCI6Ii84OTY4NTYzNC8yNzQyMDUxNTgtYmQ3NWM5MWItYzA2MS00YzEyLWJiNjUtZTNjM2Y1MjhjODVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA5MDIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNmExZDVmNDI4ODc5ZWYzMjY4ZDg2MDI2MjE0MWIyMzYyNzVhYjQzY2ZmNDA3MDk5YjA5NmNhNTMxZThlYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GcTEtfzuZx5nFf_Ds-T9vaSAPrzgdfoPteO_MAhnUZs)

May I ask if Should I download the entire code repository, or is it sufficient to download only the files you've marked?

**Comment by flashlau** [comment]
download https://huggingface.co/google-bert/bert-base-uncased, and save them in a LOCAL-FOLDER.
then set value of "text_encoder_type=LOCAL-FOLDER" in file "groundingdino/config/GroundingDINO_SwinT_OGC.py".

**Comment by AllenDun** [comment]
be sure to use absolute path

**Comment by lyf6** [comment]
@sssssshf do u know dowdload what files? all of them? and can i place it in other place instead of ~/.cache/huggingface/hub/models--bert-base-uncased/

**Comment by wuzuowuyou** [comment]
> om huggingfa

cannot open the link
