### ISSUE TITLE
export GroundinoModel to onnx

### ISSUE THREAD

**Issue by yurikobyzev** [IDEA-Research/GroundingDINO#223]
Hello, I have problem with export of GroundingDino to onnx and later to openvino with
this script (installed as in  https://blog.openvino.ai/blog-posts/enable-openvino-tm-optimization-for-groundingdino):

python demo/export_openvino.py -c groundingdino/config/GroundingDINO_SwinT_OGC.py -p weights/groundingdino_swint_ogc.pth -o weights/

this script (export_openvino.py) first try to export model to onnx and fails with error:
=================error log:
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Traceback (most recent call last):
  File "/home/cnn/projects/GroundingDINO/demo/export_openvino.py", line 92, in <module>
    export_openvino(model, output_dir)
  File "/home/cnn/projects/GroundingDINO/demo/export_openvino.py", line 53, in export_openvino
    torch.onnx.export(
  File "/home/cnn/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/home/cnn/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/cnn/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1113, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/cnn/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 989, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/cnn/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 893, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/cnn/.local/lib/python3.10/site-packages/torch/jit/_trace.py", line 1268, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/cnn/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/cnn/.local/lib/python3.10/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/cnn/.local/lib/python3.10/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/cnn/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/cnn/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
TypeError: GroundingDINO.forward() takes from 2 to 3 positional arguments but 7 were given
=====================Error Log ends here

when Look inside script i see:
#export onnx model
    torch.onnx.export(
    model,
    f="./grounded.onnx",
    args=(img, input_ids, attention_mask, position_ids, token_type_ids, text_token_mask), #, zeros, ones),
    input_names=["img" , "input_ids", "attention_mask", "position_ids", "token_type_ids", "text_token_mask"],
    output_names=["logits", "boxes"],
    dynamic_axes=dynamic_axes,
    opset_version=16)

    #convert_model returns an openvino.runtime.Model object

And suppose that error is here...
My aim was obtain onnx version of GDino model and I'm looking for correct code snippet.
This script is for Intel NCS 2 and also would be interesting if it works.
I don't understand why there is no correspondence with forward arguments of model...

Can somebody help me understand why it does not export to onnx and how to improve it?  the package installed correctly and i have no problem with inference of pytorch model of Grounding Dino.

Thank you!

**Comment by Monoclinic** [comment]
Hello, I meet the same problem.
I suppose that you should try this repo [](https://github.com/wenyi5608/GroundingDINO) instead of the official one.
You can see the author have made some changes on the model input, thus the input would be 7 (instead of 2 or 3).
[](https://github.com/wenyi5608/GroundingDINO/commit/3bb02a9cf146abb819eda3b763b282a5c50fc45f)

You can just replace `groundingdino/models/GroundingDINO/groundingdino.py` in this repo by the aforementioned one.
Then you can export the onnx suceessfully, but I haven't tested if the output is the same as pytorch.

**Comment by yurikobyzev** [comment]
O, thank you for reply! I will try it with this repo https://github.com/wenyi5608/GroundingDINO

**Comment by Fatemehkiasaveh** [comment]
does anyone know how to convert this model fushh7/llmdet_swin_tiny_hf to onnx?
