### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 2878: illegal multibyte sequence

### ISSUE THREAD

**Issue by jazelly** [IDEA-Research/GroundingDINO#347]
OS: windows 11

Run `pip install groundingdino-py==0.4.0`

Error log:
```
Collecting groundingdino-py==0.4.0 (from -r .\requirements_versions.txt (line 23))
  Using cached groundingdino-py-0.4.0.tar.gz (82 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\31711\AppData\Local\Temp\pip-install-2x73ik2j\groundingdino-py_a28a34501a2442f7b87275b504b4a439\setup.py", line 41, in <module>
          readme = readme_file.read()
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 2878: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

**Comment by chobitpapa** [comment]
I have the same problem. Since I need this package urgently, I solve it manually.
1. Download the package from [pypi.org(https://pypi.org/project/groundingdino-py/#files), unzip it, and modify the setup.py file. Change `open('README.md')` to `open('README.md', encoding='utf-8')`.
2. Compress the folder into a zip package, and then execute `pip install groundingdino-py-0.4.0.zip`.
*This is only for reference by novices who need to use it urgently like me.*

**Comment by 712123846456zcj** [comment]
> 我也遇到同样的问题，因为急需这个包，所以手动解决了。
> 
> 1. [从pypi.org](https://pypi.org/project/groundingdino-py/#files)下载包，解压，修改setup.py文件，`open('README.md')`改为`open('README.md', encoding='utf-8')`。
> 2. 将文件夹压缩成zip包，然后执行`pip install groundingdino-py-0.4.0.zip`。
>    _这个仅供和我一样急需使用的新手参考。_
> 
> 我也有同样的问题，我比较着急需要这个包，就先自己手动解决。 1、先从[pypi.org](https://pypi.org/project/groundingdino-py/#files)下载包，解压后`setup.py`文件，将`open('README.md')`修改成`open('README.md', encoding='utf-8')`。 2、将文件夹压缩成zip格式包，然后执行`pip install groundingdino-py-0.4.0.zip`。 只提供给和我一样着急使用的新手参考。


https://github.com/712123846456zcj/python_whl_fix/tree/main/AIGC
my repack whl:[groundingdino_py-0.4.0-py2.py3-none-any.whl](https://github.com/712123846456zcj/python_whl_fix/blob/main/AIGC/groundingdino_py-0.4.0-py2.py3-none-any.whl)

Sorry, I'm late.
