### ISSUE TITLE
packaging.version.InvalidVersion: Invalid version: '0.10.1,<0.11'

### ISSUE THREAD

**Issue by SkalskiP** [IDEA-Research/GroundingDINO#7]
When executing:

```
!python demo/inference_on_a_image.py \
  -c {CONFIG_PATH} \
  -p {WEIGHTS_PATH} \
  -i {IMAGE_NAME} \
  -o {OUTPUT_IMAGE_NAME} \
  -t "dog"
```

I got:

```
Traceback (most recent call last):
  File "/content/GroundingDINO/demo/inference_on_a_image.py", line 10, in <module>
    from groundingdino.models import build_model
  File "/content/GroundingDINO/groundingdino/models/__init__.py", line 8, in <module>
    from .GroundingDINO import build_groundingdino
  File "/content/GroundingDINO/groundingdino/models/GroundingDINO/__init__.py", line 15, in <module>
    from .groundingdino import build_groundingdino
  File "/content/GroundingDINO/groundingdino/models/GroundingDINO/groundingdino.py", line 24, in <module>
    from transformers import AutoTokenizer, BertModel, BertTokenizer, RobertaModel, RobertaTokenizerFast
  File "/usr/local/lib/python3.9/dist-packages/transformers/__init__.py", line 43, in <module>
    from . import dependency_versions_check
  File "/usr/local/lib/python3.9/dist-packages/transformers/dependency_versions_check.py", line 41, in <module>
    require_version_core(deps[pkg])
  File "/usr/local/lib/python3.9/dist-packages/transformers/utils/versions.py", line 101, in require_version_core
    return require_version(requirement, hint)
  File "/usr/local/lib/python3.9/dist-packages/transformers/utils/versions.py", line 92, in require_version
    if want_ver is not None and not ops[op](version.parse(got_ver), version.parse(want_ver)):
  File "/usr/local/lib/python3.9/dist-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/usr/local/lib/python3.9/dist-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '0.10.1,<0.11'
```

Any idea how to solve it?

**Comment by fkodom** [comment]
@SkalskiP I had the same issue.  Installing `packaging==21.3` solved it for me.  See this similar issue from `ComVis/latent-diffusion`:
https://github.com/CompVis/latent-diffusion/issues/207#issuecomment-1377329827

Newer versions of `packaging` are apparently more strict about semantic versioning formats.

**Comment by Jeiyoon** [comment]
@fkodom you are my life saver
