### ISSUE TITLE
Running GroundingDINO Inference

### ISSUE THREAD

**Issue by XiaoCC** [IDEA-Research/GroundingDINO#95]
秋叶整合包报错请问下要怎么修复  调试了2天了还没弄好
Running GroundingDINO Inference
Initializing GroundingDINO GroundingDINO_SwinT_OGC (694MB)
final text_encoder_type: bert-base-uncased
Traceback (most recent call last):
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\sam.py", line 248, in dino_predict
    boxes_filt, install_success = dino_predict_internal(input_image, dino_model_name, text_prompt, box_threshold)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 136, in dino_predict_internal
    dino_model = load_dino_model(dino_model_name)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 83, in load_dino_model
    dino = build_model(args)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\__init__.py", line 17, in build_model
    model = build_func(args)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\GroundingDINO\groundingdino.py", line 372, in build_groundingdino
    model = GroundingDINO(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\models\GroundingDINO\groundingdino.py", line 108, in __init__
    self.bert = get_tokenlizer.get_pretrained_language_model(text_encoder_type)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\groundingdino\util\get_tokenlizer.py", line 23, in get_pretrained_language_model
    return BertModel.from_pretrained(text_encoder_type)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\modeling_utils.py", line 2301, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\modeling_utils.py", line 413, in load_state_dict
    return safe_load_file(checkpoint_file)
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\safetensors\torch.py", line 101, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: shape '[30522, 768]' is invalid for input of size 2822882
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by shibuwu** [comment]
Having the same issue with Grounding Dino. Any updates?
